sudo: required
services: 
  - docker

before_install: 
  - docker build -t bigiayomide/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bigiayomide/react-test npm test -- --coverage


after_success:
  - docker build -t  bigiayomide/multi-client ./client
  - docker build -t  bigiayomide/multi-nginx ./nginx
  - docker build -t  bigiayomide/multi-server ./server
  - docker build -t  bigiayomide/multi-worker ./worker
  - echo "$Password" | docker login -u "$Username" --password-stdin
  - docker push bigiayomide/multi-nginx
  - docker push bigiayomide/multi-client
  - docker push bigiayomide/multi-server
  - docker push bigiayomide/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-doxker
  env: MultiDoxker-env
  bucket_name: elasticbeanstalk-us-west-2-734462768959
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET